### ISSUE TITLE
Can I import a function which is written in a ts or tsx file

### ISSUE THREAD

**Issue by nuymax** [Galooshi/emacs-import-js#29]
I wrote a next-js page which displays a `Example` component.

`pages/index.tsx`
```js
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
      </Head>
      <main>
        <Example />
      </main>
    </>
  )
}
```

And I put the `components/Example.tsx` like this.

```js
export default function Example() {
  return (
    <div>
      <p>hello </p>
    </div>
  )
}
```

Then I want to import the Example component, and I run the `M-x import-js-import` at the index.ts buffer. 

But I can't import the Example function.

Is it supported typescript?

**Comment by kevinkehl** [comment]
Sorry this was a while ago, but importjs now fully supports typescript. Let us know if there are any continuing issues.
