### ISSUE TITLE
Searching for program: No such file or directory, importjsd 

### ISSUE THREAD

**Issue by the-moriarty** [Galooshi/emacs-import-js#30]
Already installed the npm package.

Changing this function fix:
(after! import-js
;;;###autoload
  (defun run-import-js ()
    "Start the import-js daemon"
    (interactive)
    (kill-import-js)
    (let ((process-connection-type nil))
      (setq import-js-process (start-process "import-js" nil "importjs" "start" (format "--parent-pid=%s" (emacs-pid))))
      (set-process-filter import-js-process 'import-js-handle-data))))

**Comment by kevinkehl** [comment]
Same issue as in #31, import-js@5.0 removed in favor of `importjs`.

Should be fixed in 3.0.0.
