### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by LionyxML** [Galooshi/emacs-import-js#33]
This is the melpa description of the package I just installed:

```
Status: Available from melpa -- Install
    Archive: melpa
    Version: 20220215.1948
     Commit: d2bbb53f96395415f9f01de4fa88d82c1f59ba63
    Summary: Import Javascript dependencies
   Requires: grizzl-0.1.0, emacs-24
   Homepage: http://github.com/Galooshi/emacs-import-js/
   Keywords: javascript 
 Maintainer: Kevin Kehl <kevin.kehl@gmail.com>
     Author: Kevin Kehl <kevin.kehl@gmail.com>

Quick start:
run-import-js

Bind the following commands:
import-js-import
import-js-goto

For a detailed introduction see:
http://github.com/Galooshi/emacs-import-js/blob/master/README.md
```

Then `M-x run-import-js` returns on the message buffer:
`apply: Searching for program: No such file or directory, importjsd`

I do have importjs installed globally with npm:
```
>> importjs --version
5.0.0
```

And from inside emacs I can actually run it with e-shell.

I noticed the step 2 on README points to itself, so I can't see if I am missing some config.

Any help?

Thanks!

**Comment by kevinkehl** [comment]
@LionyxML it looks like you aren't configured to use the latest version; the previous version would be looking for `importjsd`. I just installed the latest from melpa (`20220215.1948`, installed using `package.el`), and verified that `run-import-js` is starting the daemon with `importjs`, not `importjsd`.

**Comment by kevinkehl** [comment]
If you run `M-x describe-function <Enter> run-import-js` make sure its pointed at the latest version. If it is and still not working let me know, might be something weird going on with the version.

**Comment by LionyxML** [comment]
I guess I forgot do run a Melpa update "before" I installed the package.

I removed the package. Updated Melpa. Installed import-js again. And it is working now.

Thanks! :)
