### ISSUE TITLE
Using "cd" to change directory for `call-process` breaks helm-find-files

### ISSUE THREAD

**Issue by joefiorini** [Galooshi/emacs-import-js#4]
I use `helm-find-files` (a default package in Spacemacs) to browse directories. It lists all files in the current buffer file's directory.

When I run `import-js-import` and then execute `helm-find-files` it now starts me in my `import-js-project-root` instead of the current buffer file's directory. Regardless of plugins, mutating global state in a plugin like this seems like a scary idea.

According to [the emacs documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Synchronous-Processes.html), `call-process` uses the `default-directory` variable as its working directory. We should be able to wrap the `call-process` call in a `let` and change it just for the scope of this call (similar to [this SO post](http://stackoverflow.com/a/23164876)).

I'd like to send a PR with this change, but I'm still a bit of an Emacs newb and not sure how to test package changes on my local filesystem. Posting here in case someone else can get to it before I can figure all that out.

**Comment by kevinkehl** [comment]
@joefiorini I've noted similar problems as well, and you're right that setting global state seems a bit heavy -handed. Would love to see a PR for this.

To test your version of the package, I usually just use `M-x load-file <ret> <path>`.

**Comment by kevinkehl** [comment]
Closed via d12799c5 https://github.com/Galooshi/emacs-import-js/pull/15
