### ISSUE TITLE
cd: No such directory found via CDPATH environment variable

### ISSUE THREAD

**Issue by linchen2chris** [Galooshi/emacs-import-js#6]
I use importjs in terminal, it works fine:
`chris2@W530-chris:~/Desktop/uhs$ 
importjs word NormalButton src/containers/PatientDetail/FollowUpRecordView/HomeFollowupDetailView/index.js
`
{"messages":["Imported `../../../../components/NormalButton (main: index.js)`"],"fileContent":"/**\n * Created by isaac on 16/4/29.\n............
but when I use importjs in my emacs it warn: cd: No such directory found via CDPATH environment variable

**Comment by linchen2chris** [comment]
I config the project root with absolute path (replace ~ with /home/chris2/) it works fine now

**Comment by lencioni** [comment]
@linchen2chris Thanks for opening the issue and coming back to post your solution so others can benefit. Have a great day!
